### ISSUE TITLE
Friendly AI

### ISSUE THREAD

**Issue by InNoHurryToCode** [Titanfall-Mods/Icepick-Core-Mods#2]
**Description**
Allow player to spawn friendly AI, such as milita spectres / soldiers.

**How this can be done**
Make 2 SpawnNpc functions:
- Friendly AI
- Hostile AI

During the tests that I've conducted, all the soldiers and robots can spawn as militia. However, they sometimes work and somtimes don't. Idk why. None of the titans worked so far, requires research.

**Comment by Tempty1531** [comment]
how
